"""empty message

Revision ID: 06b5afc2e1ec
Revises: f124c1ad2701
Create Date: 2021-01-19 16:18:36.397528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06b5afc2e1ec'
down_revision = 'f124c1ad2701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.drop_column('shows', 'che')
    op.drop_column('shows', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('che', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('shows', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
