"""empty message

Revision ID: 4192c431ec89
Revises: 2d5e5838ba51
Create Date: 2021-01-19 11:16:43.431505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4192c431ec89'
down_revision = '2d5e5838ba51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
