"""empty message

Revision ID: 8d395419b3cd
Revises: 4192c431ec89
Create Date: 2021-01-19 13:00:11.229361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d395419b3cd'
down_revision = '4192c431ec89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_date')
    # ### end Alembic commands ###
