"""empty message

Revision ID: a4c6de10540f
Revises: 06b5afc2e1ec
Create Date: 2021-01-19 16:25:10.704689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c6de10540f'
down_revision = '06b5afc2e1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_date')
    # ### end Alembic commands ###
