"""empty message

Revision ID: f124c1ad2701
Revises: 8d395419b3cd
Create Date: 2021-01-19 16:06:13.059067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f124c1ad2701'
down_revision = '8d395419b3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('che', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'che')
    # ### end Alembic commands ###
